-- SEED — sub-treatments imported from the umbrella pages (EN + AR).
-- Run ONCE in Supabase SQL Editor. Re-running updates by slug.
alter table public.treatments add column if not exists page_url text;
insert into public.treatments
  (slug, category, parent_slug, name_en, name_ar, description_en, description_ar, image_url, page_url, sort_order, is_active)
values
  ('tesla-former','body-shaping','body-shaping','Tesla Former','Tesla Former في مصر','يبني العضلات ويحرق الدهون باستخدام تقنية الموجات الكهرومغناطيسية المركّزة — يعادل آلاف تمارين البطن في جلسة واحدة.','يبني العضلات ويحرق الدهون باستخدام تقنية الموجات الكهرومغناطيسية المركّزة — يعادل آلاف تمارين البطن في جلسة واحدة.','assets/images/sub-treatments/tesla-former.jpg','treatments/body-shaping/tesla-former.html',1,true),
  ('emtone','body-shaping','body-shaping','EMTONE','EMTONE — علاج السيلوليت','The first device to simultaneously treat all major cellulite causes — using radiofrequency and targeted pressure.','أول جهاز يعالج كل أسباب السيلوليت في وقت واحد — باستخدام الموجات الراديوية والضغط المستهدف.','assets/images/sub-treatments/emtone.jpg','treatments/body-shaping/emtone.html',2,true),
  ('body-fx','body-shaping','body-shaping','Body FX','Body FX في مصر','Non-invasive radiofrequency body contouring that reduces fat, tightens skin, and smooths cellulite — all in one device.','نحت الجسم بالموجات الراديوية بدون تدخل جراحي — بيقلل الدهون ويشدّ البشرة ويخفف السيلوليت في جهاز واحد.','assets/images/sub-treatments/body-fx.jpg','treatments/body-shaping/body-fx.html',3,true),
  ('clatuu-alpha','body-shaping','body-shaping','Clatuu Alpha','Clatuu Alpha في مصر','تجميد الدهون المتقدم — تطبيقات 360° بتستهدف الدهون العنيدة اللي مش بتروح بالحمية أو الرياضة.','تجميد الدهون المتقدم — تطبيقات 360° بتستهدف الدهون العنيدة اللي مش بتروح بالحمية أو الرياضة.','assets/images/sub-treatments/clatuu-alpha.jpg','treatments/body-shaping/clatuu-alpha.html',4,true),
  ('hifu-body','body-shaping','body-shaping','HIFU Body','HIFU Body في مصر','Non-surgical body lifting and tightening with high-intensity focused ultrasound — for arms, abdomen, thighs, and more.','شد ورفع الجسم بدون جراحة باستخدام الموجات فوق الصوتية المركّزة عالية الكثافة — للأذرع، البطن، الفخذين، والمناطق الأخرى.','assets/images/sub-treatments/hifu-body.jpg','treatments/body-shaping/hifu-body.html',5,true),
  ('morpheus8-body','body-shaping','body-shaping','Morpheus8 Body','Morpheus8 Body في مصر','Microneedling + radiofrequency for deep skin remodeling on the body — stretch marks, laxity, and texture.','الميكرونيدلينج + الموجات الراديوية لإعادة بناء البشرة بعمق على الجسم — لعلامات التمدد، الترهل، والملمس.','assets/images/sub-treatments/morpheus8-body.jpg','treatments/body-shaping/morpheus8-body.html',6,true),
  ('botox','skin-rejuvenation','skin-rejuvenation','Botox','البوتوكس في مصر','Smooths wrinkles and prevents new ones by relaxing targeted facial muscles. Refreshed, not frozen.','يخفي التجاعيد ويمنع ظهور الجديدة عن طريق ارتخاء عضلات الوجه المستهدفة. إطلالة منتعشة طبيعية.','assets/images/sub-treatments/botox.jpg','treatments/skin-rejuvenation/botox.html',7,true),
  ('filler','skin-rejuvenation','skin-rejuvenation','Dermal Fillers','الفيلر في مصر','Restores lost volume in lips, cheeks, jawline, and under-eye — for natural, balanced results.','يستعيد الحجم المفقود في الشفايف، الخدود، الفك، وتحت العين — لنتائج طبيعية متوازنة.','assets/images/sub-treatments/filler.jpg','treatments/skin-rejuvenation/filler.html',8,true),
  ('skin-boosters','skin-rejuvenation','skin-rejuvenation','Skin Boosters','Skin Boosters في مصر','Deep hyaluronic hydration injections that restore glow, elasticity, and quality from within.','حقن ترطيب عميق بحمض الهيالورونيك بتستعيد الإشراقة، المرونة، وجودة البشرة من الداخل.','assets/images/sub-treatments/skin-boosters.jpg','treatments/skin-rejuvenation/skin-boosters.html',9,true),
  ('biostimulators','skin-rejuvenation','skin-rejuvenation','Biostimulators','Biostimulators في مصر','Stimulate your own collagen for firmer, denser skin and long-lasting natural rejuvenation.','تحفّز إنتاج الكولاجين الطبيعي لبشرة أكثر شداً وكثافة، مع تجديد طبيعي طويل المدى.','assets/images/sub-treatments/biostimulators.jpg','treatments/skin-rejuvenation/biostimulators.html',10,true),
  ('hydrafacial','skin-rejuvenation','skin-rejuvenation','Hydrafacial','الهيدرافيشيال في مصر','Deep cleansing, exfoliation, and hydration in one session. Instant glow with zero downtime.','تنظيف عميق، تقشير، وترطيب في جلسة واحدة. إشراقة فورية بدون فترة نقاهة.','assets/images/sub-treatments/hydrafacial.jpg','treatments/skin-rejuvenation/hydrafacial.html',11,true),
  ('iface','skin-rejuvenation','skin-rejuvenation','iFace','iFace','Our signature combination — Hydrafacial + Forma in one session for cleansing, hydration, and skin tightening.','البروتوكول المميز عندنا — هيدرافيشيال + فورما في جلسة واحدة للتنظيف، الترطيب، وشد البشرة.','assets/images/sub-treatments/iface.jpg','treatments/skin-rejuvenation/iface.html',12,true),
  ('forma','skin-rejuvenation','skin-rejuvenation','Forma Skin Tightening','الفورما لشد البشرة','Radiofrequency skin tightening — gentle warming that stimulates collagen and firms over time.','شد البشرة بالموجات الراديوية — حرارة لطيفة بتحفّز الكولاجين وبتشدّ مع الوقت.','assets/images/sub-treatments/forma.jpg','treatments/skin-rejuvenation/forma.html',13,true),
  ('hifu','skin-rejuvenation','skin-rejuvenation','HIFU – Non-Surgical Face Lift','الهايفو – شد الوجه بدون جراحة','High-Intensity Focused Ultrasound for non-surgical lifting and tightening at the deepest skin layers.','موجات فوق صوتية مركّزة عالية الكثافة لشد ورفع البشرة بدون جراحة في أعمق الطبقات.','assets/images/sub-treatments/hifu.jpg','treatments/skin-rejuvenation/hifu.html',14,true),
  ('morpheus8','skin-rejuvenation','skin-rejuvenation','Morpheus8','Morpheus8 في مصر','Microneedling + radiofrequency for deep skin remodeling — scars, texture, pores, and tightening.','ميكرونيدلينج + موجات راديوية لإعادة بناء عميقة للبشرة — للندبات، الملمس، المسام، والشد.','assets/images/sub-treatments/morpheus8.jpg','treatments/skin-rejuvenation/morpheus8.html',15,true),
  ('laser','skin-rejuvenation','skin-rejuvenation','Laser Treatments','علاجات الليزر','Hair removal, skin resurfacing, pigmentation correction.','إزالة الشعر، تجديد البشرة، علاج التصبغات.','assets/images/laser.jpg','treatments/laser.html',16,true),
  ('votiva','skin-rejuvenation','skin-rejuvenation','Votiva','فوتيفا','Non-surgical intimate wellness — tightening, urinary incontinence, and post-childbirth restoration.','تجميل المنطقة الحساسة بدون جراحة — شد، علاج سلس البول، واستعادة ما بعد الولادة.','assets/images/votiva.jpg','treatments/votiva.html',17,true),
  ('exosomes','hair-restoration','hair-restoration','Exosomes','Exosomes','The latest Korean technology for hereditary baldness and chronic hair loss — cellular communication signals that reprogram the follicle for new, healthy growth.','أحدث تكنولوجيا كورية لعلاج الصلع الوراثي وتساقط الشعر المزمن — إشارات تواصل خلوي بتعيد برمجة البصيلة لنمو شعر جديد وصحي.','assets/images/sub-treatments/exosomes.jpg','treatments/hair-restoration/exosomes.html',18,true),
  ('growth-factor','hair-restoration','hair-restoration','Growth Factor','Growth Factor','Concentrated multivitamin and peptide injections — feed the follicle, stop the shedding, fill thinning gaps, and restore healthy hair quality.','حقن فيتامينات وببتيدات مركزة — بتغذي البصيلة، بتوقف التساقط، بتملي فراغات التخفيف، وبترجع للشعر جودته الصحية.','assets/images/sub-treatments/growth-factor.jpg','treatments/hair-restoration/growth-factor.html',19,true)
on conflict (slug) do update set category=excluded.category, parent_slug=excluded.parent_slug,
  name_en=excluded.name_en, name_ar=excluded.name_ar, description_en=excluded.description_en,
  description_ar=excluded.description_ar, image_url=excluded.image_url, page_url=excluded.page_url,
  sort_order=excluded.sort_order, is_active=excluded.is_active;
