-- SEED — your 7 doctors (EN + AR). Department is a list (text[]).
-- Run AFTER migration-3.sql. Re-running safely updates by slug.
insert into public.doctors
  (slug, name_en, name_ar, specialty_en, specialty_ar, bio_en, bio_ar, image_url, department, sort_order, is_active)
values
  ('dr-sara-abdelhameed','Dr. Sara Abdelhameed','د. سارة عبدالحميد','Body Contouring Specialist','أخصائي نحت وتنسيق القوام','Clinical Nutrition Consultant — Cairo University. 12+ years experience, 50,000+ successful cases in non-surgical body sculpting.','استشاري التغذية العلاجية — جامعة القاهرة. خبرة تتجاوز 12 عاماً وأكثر من 50,000 حالة ناجحة في نحت الجسم بدون جراحة.','assets/images/doctors/dr-sara-abdelhameed.jpg',array['body']::text[],1,true),
  ('dr-rana-ibrahim-sultan','Dr. Rana Ibrahim Sultan','د. رنا إبراهيم سلطان','Clinical Nutrition Specialist & Body Sculpting Expert','أخصائي تغذية علاجية وخبيرة نحت الجسم','Clinical Nutrition Specialist and certified Body Sculpting expert. An integrated approach combining evidence-based clinical nutrition with non-surgical body contouring for sustainable results.','ماجستير العلاج الطبيعي — جامعة القاهرة. خبرة 8+ سنوات، قرابة 10,000 حالة تجمع بين التغذية ونحت الجسم بدون جراحة.','assets/images/doctors/dr-rana-ibrahim-sultan.jpg',array['body']::text[],2,true),
  ('dr-ehssan-rabie','Dr. Ehssan Rabie','د. إحسان ربيع','Clinical Nutrition & Body Reshaping Specialist','أخصائي تغذية علاجية ونحت القوام','MSc Cairo University, PhD candidate. 13 years at Kasr Al-Ainy. 10+ years in non-surgical body reshaping and medical weight management.','ماجستير جامعة القاهرة، مسجلة للدكتوراه. 13 سنة في القصر العيني. خبرة 10+ سنوات في نحت القوام بدون جراحة وإدارة الوزن طبياً.','assets/images/doctors/dr-ehssan-rabie.jpg',array['body']::text[],3,true),
  ('dr-rana-safwat','Dr. Rana Safwat','د. رنا صفوت','Dermatology, Laser & Aesthetic Specialist','أخصائي الجلدية والليزر والتجميل','MSc Dermatology — Ain Shams University. 12+ years in dermatology, laser, injectables, and non-surgical aesthetics.','ماجستير الجلدية — جامعة عين شمس. خبرة 12+ عاماً في الجلدية، الليزر، الحقن، والتجميل غير الجراحي.','assets/images/doctors/dr-rana-safwat.jpg',array['skin']::text[],4,true),
  ('dr-marwa-magdy','Dr. Marwa Magdy','د. مروة مجدي','Aesthetic Dermatologist & Advanced Injector','استشاري الجلدية والحقن غير الجراحي','MSc Dermatology — Ain Shams. 10+ years aesthetic experience, 5,000+ Morpheus8 cases. Specialist in combination treatments.','ماجستير الجلدية — عين شمس. خبرة 10+ سنوات في التجميل، 5,000+ حالة Morpheus8. متخصصة في العلاجات المركبة.','assets/images/doctors/dr-marwa-magdy.jpg',array['skin']::text[],5,true),
  ('dr-nesma-samir','Dr. Nesma Samir','د. نسمة سمير','Laser Aesthetic Dermatology Specialist','أخصائي جلدية وتجميل بالليزر','MBBCh Kasr Al-Ainy + 2 specialized diplomas. 12 years in laser dermatology, 200+ cases of acne, pigmentation, melasma, and scars.','بكالوريوس قصر العيني + دبلومتين متخصصتين. 12 سنة في الليزر التجميلي، 200+ حالة في حب الشباب، التصبغات، الكلف، والندبات.','assets/images/doctors/dr-nesma-samir.jpg',array['skin','hair']::text[],6,true),
  ('dr-hadeel-hanee','Dr. Hadeel Hanee','د. هديل هانئ','Consultant Plastic, Burn & Maxillofacial Surgery','استشاري جراحة التجميل والحروق وجراحة الوجه والفكين','Lecturer at Ain Shams · Fellow University of Maryland (Shock Trauma) · Surgical Oncologist at Baheya. 10+ years, 3,500+ cases.','مدرس بعين شمس · زميل جامعة ميريلاند (الشوك تروما) · جراحة أورام ببهية. 10+ سنوات، 3,500+ حالة.','assets/images/doctors/dr-hadeel-hanee.jpg',array['surgical']::text[],7,true)
on conflict (slug) do update set name_en=excluded.name_en, name_ar=excluded.name_ar,
  specialty_en=excluded.specialty_en, specialty_ar=excluded.specialty_ar,
  bio_en=excluded.bio_en, bio_ar=excluded.bio_ar, image_url=excluded.image_url,
  department=excluded.department, sort_order=excluded.sort_order, is_active=excluded.is_active;
