-- ============================================================
--  Hollywood Clinic — dashboard setup
--  Run this ONCE in Supabase → SQL Editor → New query → Run.
--  Safe to run again; it never drops or overwrites your data.
--
--  It creates everything the dashboard needs to:
--    1. fill in the extra sections on a doctor's page
--    2. replace any image or video on any page
--    3. add new photos / videos to a page's gallery
-- ============================================================


-- ── 1. Doctor page sections ─────────────────────────────────
-- One item per line. "|" splits a line into its parts:
--   why_*       badge | label | text     e.g.  12+ | Experience | Years in body contouring.
--   services_*  one service per line
--   tech_*      device | what it does    e.g.  EMTONE | Cellulite treatment and skin firming.
--   faq_*       question | answer
-- Leave a column empty and that section is hidden on the page.

alter table public.doctors add column if not exists why_en       text;
alter table public.doctors add column if not exists why_ar       text;
alter table public.doctors add column if not exists services_en  text;
alter table public.doctors add column if not exists services_ar  text;
alter table public.doctors add column if not exists tech_en      text;
alter table public.doctors add column if not exists tech_ar      text;
alter table public.doctors add column if not exists faq_en       text;
alter table public.doctors add column if not exists faq_ar       text;


-- ── 2. Replace an image or video anywhere on the site ───────
-- key   = what the page ships with: an image path without leading ../
--         (assets/images/emtone/emtone-01.jpg) or a YouTube id (H4vNpAjn3wY)
-- value = what to show instead
-- Delete a row and the original comes back.

create table if not exists public.media_overrides (
  key         text primary key,
  value       text not null,
  kind        text not null default 'image',
  note        text,
  updated_at  timestamptz default now()
);

alter table public.media_overrides enable row level security;
drop policy if exists "media_overrides read"  on public.media_overrides;
drop policy if exists "media_overrides write" on public.media_overrides;
create policy "media_overrides read"  on public.media_overrides for select using (true);
create policy "media_overrides write" on public.media_overrides for all to authenticated
  using (true) with check (true);


-- ── 3. Add new photos / videos to a gallery ─────────────────
-- page_key = the page, without leading ../ and without .html
--            e.g. treatments/body-shaping/body-fx
-- kind     = 'image' or 'video'
-- value    = an uploaded image URL, or a YouTube id

create table if not exists public.gallery_additions (
  id          bigint generated by default as identity primary key,
  page_key    text not null,
  kind        text not null default 'image',
  value       text not null,
  thumb       text,
  caption_en  text,
  caption_ar  text,
  sort_order  int  default 0,
  is_active   boolean default true,
  created_at  timestamptz default now()
);

create index if not exists gallery_additions_page_idx
  on public.gallery_additions (page_key, sort_order);

alter table public.gallery_additions enable row level security;
drop policy if exists "gallery_additions read"  on public.gallery_additions;
drop policy if exists "gallery_additions write" on public.gallery_additions;
create policy "gallery_additions read"  on public.gallery_additions for select using (is_active = true);
create policy "gallery_additions write" on public.gallery_additions for all to authenticated
  using (true) with check (true);


-- ── 4. Let visitors see services added in the dashboard ─────
-- Without this the table is readable only by signed-in staff, so a service
-- looks fine to you and is invisible to everyone else.

alter table public.service_pages enable row level security;

drop policy if exists service_pages_select_public on public.service_pages;
create policy service_pages_select_public on public.service_pages
  for select to anon, authenticated using (is_active is true);

drop policy if exists service_pages_admin_all on public.service_pages;
create policy service_pages_admin_all on public.service_pages
  for all to authenticated using (true) with check (true);

update public.service_pages set is_active = true where is_active is null;


-- ── check it worked ─────────────────────────────────────────
select 'doctors extra columns' as item,
       count(*)::text || ' of 8' as result
from information_schema.columns
where table_schema='public' and table_name='doctors'
  and column_name in ('why_en','why_ar','services_en','services_ar','tech_en','tech_ar','faq_en','faq_ar')
union all
select 'media_overrides table', case when to_regclass('public.media_overrides') is null then 'MISSING' else 'ready' end
union all
select 'gallery_additions table', case when to_regclass('public.gallery_additions') is null then 'MISSING' else 'ready' end
union all
select 'services visible to public',
       case when exists (select 1 from pg_policies
                         where schemaname='public' and tablename='service_pages'
                           and cmd='SELECT' and 'anon' = any(roles))
            then 'ready' else 'MISSING' end;
